spring:
  application:
      name=JujustsuApi
  datasource:
    url: jdbc:postgresql://localhost:5432/DATABASE_NAME
    username: USERNAME
    password: PASSWORD
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

